



DELETE	TB_MESSAGE;
DELETE	TB_USER_AUTH_TOKEN;
DELETE	TB_REPAIR_REQ_MEMO;
DELETE	TB_REPAIR_REQ_ETC_INFO;
DELETE	TB_FILE_TRANSFER_HISTORY;
DELETE	TB_REPAIR_WORK;
DELETE	TB_REPAIR_REQ;
DELETE	TB_CAR_MODEL;
DELETE	TB_VENDER;
DELETE	TB_FILE;
DELETE	TB_FILE_GROUP;
DELETE	TB_WORKER;
DELETE	TB_DEPARTMENT;
DELETE	TB_PHOTO_FILE_NAME_RULES;
DELETE	TB_CAR_REPAIR_SHOP;



DBCC CHECKIDENT(TB_CAR_REPAIR_SHOP, reseed, 0);
DBCC CHECKIDENT(TB_DEPARTMENT, reseed, 0);
DBCC CHECKIDENT(TB_WORKER, reseed, 0);
DBCC CHECKIDENT(TB_REPAIR_REQ, reseed, 0);
DBCC CHECKIDENT(TB_REPAIR_WORK, reseed, 0);
DBCC CHECKIDENT(TB_FILE_GROUP, reseed, 0);
DBCC CHECKIDENT(TB_FILE, reseed, 0);
DBCC CHECKIDENT(TB_USER_AUTH_TOKEN, reseed, 0);
DBCC CHECKIDENT(TB_FILE_TRANSFER_HISTORY, reseed, 0);


